Insert Into SC_COMUN.SE_GASTO (
	GAST_sOSE_ID, GAST_iNUMREGISTRO, GAST_dFECHA, GAST_sCTACTE_ID, GAST_tTIPOPROVEEDOR, GAST_sIDPROVEEDOR, GAST_vDETALLEGASTO, 
	GAST_tFORMAPAGO, GAST_sIDCHECKE, GAST_bESCAJACHICA, GAST_sSITUACION, 
	GAST_sUSUARIO_CREACION, GAST_vIP_CREACION, GAST_dFECHA_CREACION)
Values (
	
)